In [13]:
##### numpy索引#######
import numpy as np

#一维索引
A=np.arange(3,15) 
print(A)
print(A[3])

#二维索引
A=np.arange(3,15).reshape((3,4))
print(A)
print(A[2])  #第三行所有元素

print(A[1][1])
print(A[1,1])
print(A[1,1:3]) #第2行，2、3列

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
8
8
[8 9]


In [12]:
#逐行打印
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [14]:
#逐列打印
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [17]:
# 迭代输出
print(A.flatten())  #flatten把多维矩阵展开成一维

for item in A.flat:  #flat是一个迭代器
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [27]:
#######numpy array合并#######

# np.vstack(): 上下合并
A=np.array([1,1,1])
print(A)
print(A.shape) #A的大小是(3,) 并不是矩阵
B=np.array([2,2,2])
print(B)
C=np.vstack((A,B))
print(C)
print(C.shape)  #C的大小是(2,3)
print('\n')

# np.hstack(): 左右合并
D=np.hstack((A,B))
print(D)
print(A.shape,D.shape) 

[1 1 1]
(3,)
[2 2 2]
[[1 1 1]
 [2 2 2]]
(2, 3)


[1 1 1 2 2 2]
(3,) (6,)


In [38]:
# 扩张维度np.newaxis()
print(A)
B=A[np.newaxis,:] #列扩张
C=A[:,np.newaxis] #行扩张
print(B)   
print(C,'\n')

#矩阵大小的区别
print(A.shape,B.shape,C.shape,'\n')  


#转置的区别
print(A.T)
print(B.T)
print(C.T)

[1 1 1]
[[1 1 1]]
[[1]
 [1]
 [1]] 

(3,) (1, 3) (3, 1) 

[1 1 1]
[[1]
 [1]
 [1]]
[[1 1 1]]


In [48]:
# np.concatenate() : 合并操作需要针对多个矩阵或序列
A=np.arange(1,9).reshape(4,2)
B=np.arange(10,18).reshape(4,2)
C = np.concatenate((A,B,B,A),axis=0) #列合并
print(C,'\n')

D = np.concatenate((A,B,B,A),axis=1) # 行合并
print(D)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]] 

[[ 1  2 10 11 10 11  1  2]
 [ 3  4 12 13 12 13  3  4]
 [ 5  6 14 15 14 15  5  6]
 [ 7  8 16 17 16 17  7  8]]
