In [15]:
#########################正则表达式##########################
import re

#####分组group ID是数字，\d可以匹配；Date后是数字或特殊字符，.匹配除了换行符以外的字符
match=re.search(r'(\d+),Date:(.+)','ID:021523,Date:Jan/15/2019')
print(match.group(0)) #返回所有结果
print(match.group(1)) #返回第一个ptn的匹配结果
print(match.group(2)) #返回第二个ptn的匹配结果

#给group命名 ?P<name>
match=re.search(r'(?P<id>\d+),Date:(?P<date>.+)','ID:021523,Date:Jan/15/2019')
print(match.group('id'))
print(match.group('date'))

021523,Date:Jan/15/2019
021523
Jan/15/2019
021523
Jan/15/2019


In [16]:
#####寻找所有匹配
print(re.findall(r'r[ua]n','run ran ren'))

['run', 'ran']


In [19]:
##### 多种匹配
# | ：or   r'(a|b)'
print(re.findall(r'(run|ran)','run ran ren'))

['run', 'ran']


In [20]:
##### 替换
#re.sub(r'a','b',string)  b replace a
print(re.sub(r'r[au]ns','catches','dog runs to cat'))

dog catches to cat


In [23]:
##### 分裂
#re.split()
print(re.split(r'[,;\.]','a;b,c.d;e'))  #.代表除换行符以外的所有内容，单纯表示.则需要加反斜杠

['a', 'b', 'c', 'd', 'e']


In [24]:
#####  compile
compile_re=re.compile(r'r[au]n')   #先把需要搜索的字符进行编译
print(compile_re.search('dog ran to cat'))  #然后直接查找匹配

<_sre.SRE_Match object; span=(4, 7), match='ran'>


In [28]:
########################numpy#################################
import numpy as np

#####numpy的基本属性

# np.array 把列表转换为矩阵
array=np.array([[1,2,3],[2,3,4]])  
print(array)

# ndim 显示维度
print('number of dim:',array.ndim)

# shape 行数和列数
print('shape:',array.shape)

# size 元素个数
print('size:',array.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6


In [43]:
#####创建array

a=np.array([2,23,5]) 
print(a) #与列表相似，无逗号隔开

# dtype：指定array元素类型，int64/float16
a=np.array([2,45,7],dtype=np.float16)
print(a.dtype)

# zeros/ones/empty矩阵
a=np.zeros((3,4))
print(a)
b=np.ones((3,4))
print(b)
c=np.empty((3,4)) #数值接近于0
print(c)

# 指定范围创建array
d=np.arange(10,20,2)
print(d)
d=np.arange(12).reshape((3,4)) #0-11,生成3行4列
print(d)

# 创建线段linspace
e=np.linspace(1,10,5) #1-10,生成5个数
print(e)

[ 2 23  5]
float16
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.    3.25  5.5   7.75 10.  ]


In [46]:
##### numpy基础运算1

# 加减，次方**，三角函数
a=np.array([10,20,30,40])
b=np.arange(4)
c=a+b
print(c)
d=a**2
print(d)
e=10*np.sin(a)
print(e)

# 比大小
print(b)
print(b<3)

[10 21 32 43]
[ 100  400  900 1600]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[0 1 2 3]
[ True  True  True False]


In [57]:
##### 两种矩阵的乘法
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))
print(a)
print(b)
c1=a*b    #对应位置相乘
c2=np.dot(a,b) #矩阵运算   c2=a.dot(b)
print(c1)
print(c2)

## 随机产生的array
a=np.random.random((2,4)) #2行4列

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]


In [60]:
#求和/最大值/最小值
print(np.sum(a)) #列求和np.sum(a,axis=0)，行求和np.sum(a,axis=1)
print(np.max(a)) #同上
print(np.min(a))

4.1056756789138396
0.9506622690198463
0.029621387332578908


In [70]:
##### numpy基础运算2

# argmin/argmax:最大值/最小值的索引
A=np.arange(2,14).reshape((3,4))
print(A)
print(np.argmin(A)) 
print(np.argmax(A))

# mean/average:平均数; median:中位数;  cumsum:累加和； diff: 后一个元素与前一个元素的差
print(np.mean(A))
print(np.average(A))
print(np.median(A))
print(np.cumsum(A))
print(np.diff(A))

# 找出非0数位置的n(维数)个数组
print(np.nonzero(A))

#排序sort
A=np.arange(14,2,-1).reshape((3,4))
print(A)
print(np.sort(A)) #逐行从小到大排序

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [72]:
##### 矩阵的转置，行列转换
print(np.transpose(A))    
print(A.T)
print(A.T.dot(A))

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


In [ ]:
##### clip(a,a_min,a_max) 设定最小值、最大值区间，小于则变为a_min,大于则变为a_max,介于之间数不变
print(A)
print(np.clip(A,5,9)) 